### PR TITLE
105 Add the option popperPreventOverflowEnabled

### PR DESCRIPTION
**Pull request by dmytro-krekota**
Hi @MrFrankel, I created the pull request for the ticket https://github.com/MrFrankel/ngx-popper/issues/105.

### CODE REVIEW

**Comment by MrFrankel** [comment]
ignore the travis failure, its broken, thanks for the PR!
I think popperPreventOverflow instead of popperPreventOverflowEabled is better, it's shorter and the enabled is trivial.

**Comment by dmytro-krekota** [comment]
It looks good, thanks!

**Comment by MrFrankel** [comment]
@dmytro-krekota can set the version to release?

**Comment by dmytro-krekota** [comment]
@MrFrankel I do not sure that I can and have rules for it. What do you mean by setting the version to release?

**Comment by MrFrankel** [comment]
Ill do it, just wanted to make sure all looks good on your end

**Pull request merged**
