### PR TITLE
Move styles to the new file popper-content.css

### PR DESCRIPTION
**Pull request by dmytro-krekota**
Hi @MrFrankel. I've just moved popper content styles to a new file popper-content.css in the pull request. It needed to me because I created a separate component for opening a popper and I want to import styles from your component to my component. Now I use a workaround - I've just copied your styles to my source files.

A separate component is needed for me because I open the popper from [Highcharts](https://www.highcharts.com/) and now your library cannot do it from the box.

### CODE REVIEW

**Comment by MrFrankel** [comment]
sounds reasonable, ill merge this and try and release a version later

**Comment by MrFrankel** [comment]
@dmytro-krekota iv'e published 6.1.0-beta, can you please check it before I release a version?

**Comment by dmytro-krekota** [comment]
@MrFrankel, sure, I'll write to you later.

**Comment by dmytro-krekota** [comment]
@MrFrankel, everything works fine, but my problem is not resolved, because `npm` brings to me compiles files to js without any separate style files. So, I'll keep copied styles in my project and wait for resolving of the ticket: https://github.com/angular/angular/issues/24463
Thank you.

**Comment by steve3d** [comment]
this will not solve any problem, because no matter what you use, inline style or seperate style files, angular will always insert these styles to the last of `head` element, then your style will be loaded before the inline styles, so you will have to add `!important` to every style you modified, without `!important` your styles simply won't work.

**Pull request merged**
